version: '3.1'
services:

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: zaq1@WSX
      MYSQL_DATABASE: TwitterDb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.1
    ports:
      - 8081:80

  twitter-app-backend:
    restart: always
    build:
      context: TwitterAppBackend
      dockerfile: Dockerfile
      args:
        passwordToDbArg: "zaq1@WSX"
        baererKeyArg: "AAAAAAAAAAAAAAAAAAAAAOcaWAEAAAAA6xSmtCZ1h%2BsBLvkP9QnAXYnoda4%3DaW649bjaaReyDvln0IC2eSnajPivrk3CPnt8xzD1XcUhXTnNqw"
    image: twitter-app-backend:latest
    ports:
      - 8080:8080

networks:
  default:
volumes:
  db:
