version: '3.1'
services:

  mysql:
    container_name: twitter-app-mysql
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: zaq1@WSX
      MYSQL_DATABASE: TwitterDb
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    container_name: twitter-app-phpmyadmin
    image: phpmyadmin:5.1
    ports:
      - 8081:80
    environment:
      - PMA_HOST=twitter-app-mysql
      - PMA_PORT=3306

  backend:
    container_name: twitter-app-backend
    restart: always
    build:
      context: TwitterAppBackend
      dockerfile: Dockerfile
      args:
        dbAdressArg: "twitter-app-mysql"
        dbPortArg: "3306"
        databaseNameArg: "TwitterDb"
        loginToDbArg: "root"
        passwordToDbArg: "zaq1@WSX"
        baererKeyArg: "AAAAAAAAAAAAAAAAAAAAAOcaWAEAAAAA6xSmtCZ1h%2BsBLvkP9QnAXYnoda4%3DaW649bjaaReyDvln0IC2eSnajPivrk3CPnt8xzD1XcUhXTnNqw"

  front:
    container_name: twitter-app-front
    build:
      context: TwitterAppFront
      dockerfile: Dockerfile
    ports:
      - 4200:80

networks:
  default:
volumes:
  db:
