version: '3.1'
services:

  db:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zaq1@WSX
      MYSQL_DATABASE: TwitterDb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.1
    restart: always
    ports:
      - 8081:80

networks:
  default:
volumes:
  db: